# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Jam's Homelab
copyright: Copyright &copy; 2023 - 2025 Jam

repo_url: https://github.com/fullstackjam/k8s-gitops

theme:
  favicon: https://github.com/khuedoan/homelab/assets/27996771/d33be1af-3687-4712-a671-4370da13cc92
  name: material
  palette:
    primary: black
  features:
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - search.highlight
    - search.share

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
  - def_list
  - pymdownx.tasklist:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Installation:
    - Production:
      - installation/production/prerequisites.md
      - installation/production/external-resources.md
      - installation/production/deployment.md
    - installation/post-installation.md
  - Getting started:
    - getting-started/user-onboarding.md
  - Concepts:
    - concepts/secrets-management.md
    - concepts/certificate-management.md
    - concepts/tools-container.md
  - How-to guides:
    - how-to-guides/expose-services-to-the-internet.md
    - how-to-guides/use-both-github-and-gitea.md
    - how-to-guides/updating-documentation.md
  - Reference:
    - Architecture:
      - reference/architecture/overview.md
      - reference/architecture/networking.md
      - reference/architecture/decision-records.md
    - reference/changelog.md
    - reference/roadmap.md
    - reference/contributing.md
