apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: autoally-backend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: autoally-backend=fullstackjam/autoally-backend
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/git-branch: master
    argocd-image-updater.argoproj.io/update-strategy: newest-build
spec:
  project: default
  source:
    repoURL: https://github.com/fullstackjam/autoally-backend
    targetRevision: master
    path: helm/autoally-backend
  destination:
    name: in-cluster
    namespace: autoally-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 16m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
