apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-watchlist
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fullstackjam/flask-watchlist
    targetRevision: master
    path: helm/flask-watchlist
  destination:
    name: in-cluster
    namespace: flask-watchlist
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 16m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
