cilium_repo_url: https://helm.cilium.io
cilium_version: 1.17.2
cilium_namespace: kube-system
cilium_values:
  operator:
    replicas: 1
  # kubeProxyReplacement: true
  # kubeProxyReplacementHealthzBindAddr: '0.0.0.0:10256'
  l2announcements:
    enabled: true
  k8sServiceHost: 127.0.0.1
  k8sServicePort: 6443
  hubble:
    relay:
      enabled: true
    ui:
      enabled: true
      ingress:
        enabled: true
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - &host hubble.fullstackjam.com
        tls:
          - secretName: hubble-general-tls
            hosts:
              - *host
  securityContext:
    privileged: true
