- name: Check Kubernetes installation status
  hosts: metal
  roles:
    - prerequisites
  tasks:
    - name: Check if Kubernetes is already installed
      command: kubectl cluster-info
      register: k8s_check
      failed_when: false
      changed_when: false

    - name: Success message if Kubernetes is already installed
      debug:
        msg: "✅ Kubernetes is already installed and running. Proceeding with cluster configuration."
      when: k8s_check.rc == 0

    - name: Fail if Kubernetes is not installed
      fail:
        msg: |
          ❌ Kubernetes is not installed or not running.
          
          Please install Kubernetes first using the kubespray repository:
          https://github.com/fullstackjam/kubespray
          
          After installation is complete, return to this repository to continue
          with the homelab configuration.
      when: k8s_check.rc != 0
