all:
  vars:
    control_plane_endpoint: 192.168.2.55
    load_balancer_ip_pool:
      - 192.168.2.160/28
metal:
  children:
    masters:
      hosts:
        homelab-5: {ansible_host: 192.168.2.55, mac: '48:f3:17:15:00:64', disk: sda, network_interface: enp1s0}
    workers:
      hosts:
        homelab-7: {ansible_host: 192.168.2.57, mac: '48:f3:17:14:ff:b4', disk: sda, network_interface: enp1s0}
