rook-ceph:
  monitoring:
    enabled: true
rook-ceph-cluster:
  monitoring:
    enabled: true
    createPrometheusRules: true
  cephClusterSpec:
    storage:
      useAllNodes: false
      useAllDevices: false
      deviceFilter: "^nvme"
      nodes:
      - name: "homelab-5"
        devices:
        - name: "/dev/nvme0n1"
      - name: "homelab-6"
        devices:
        - name: "/dev/nvme0n1"
      - name: "homelab-7"
        devices:
        - name: "/dev/nvme0n1"
    mon:
      count: 3
    mgr:
      count: 3
    dashboard:
      ssl: false
    logCollector:
      enabled: false
    removeOSDsIfOutAndSafeToRemove: true
    resources:
      mgr:
        limits:
          memory: "1Gi"
        requests:
          cpu: "100m"
          memory: "512Mi"
      mon:
        limits:
          memory: "2Gi"
        requests:
          cpu: "100m"
          memory: "100Mi"
      osd:
        limits:
          memory: "4Gi"
        requests:
          cpu: "100m"
          memory: "512Mi"
  cephBlockPools:
    - name: standard-rwo
      spec:
        replicated:
          size: 3
      storageClass:
        enabled: true
        name: standard-rwo
        isDefault: true
        allowVolumeExpansion: true
        parameters:
          imageFeatures: layering,fast-diff,object-map,deep-flatten,exclusive-lock
          csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
          csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
          csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
          csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
  cephBlockPoolsVolumeSnapshotClass:
    enabled: true
    isDefault: true
  cephFileSystems:
    - name: standard-rwx
      spec:
        metadataPool:
          replicated:
            size: 3
        dataPools:
          - name: data0
            replicated:
              size: 3
        metadataServer:
          activeCount: 1
          activeStandby: true
          resources:
            limits:
              memory: "4Gi"
            requests:
              cpu: "100m"
              memory: "100Mi"
          priorityClassName: system-cluster-critical
      storageClass:
        enabled: true
        name: standard-rwx
        isDefault: false
        allowVolumeExpansion: true
        pool: data0
        parameters:
          csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
          csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
          csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
          csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
  cephFileSystemVolumeSnapshotClass:
    enabled: true
    isDefault: false
  cephObjectStores: []
  ingress:
    dashboard:
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      host:
        name: ceph.fullstackjam.com
        path: /
        pathType: Prefix
      tls:
      - hosts:
          - ceph.fullstackjam.com
        secretName: ceph-general-tls
