harbor:
  expose:
    type: ingress
    tls:
      enabled: true
      certSource: secret
      secret:
        secretName: "harbor-general-tls"
    ingress:
      hosts:
        core: harbor.fullstackjam.com
      controller: default
      className: "nginx"
      annotations:
        ingress.kubernetes.io/ssl-redirect: "true"
        ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: "homelab-tunnel.fullstackjam.com"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"

  externalURL: https://harbor.fullstackjam.com
  persistence:
    enabled: true
    resourcePolicy: "keep"
    persistentVolumeClaim:
      registry:
        existingClaim: ""
        storageClass: "standard-rwx"
        subPath: ""
        accessMode: ReadWriteMany
        size: 50Gi
        annotations: {}
      jobservice:
        jobLog:
          existingClaim: ""
          storageClass: "standard-rwx"
          subPath: ""
          accessMode: ReadWriteMany
          size: 1Gi
          annotations: {}
      database:
        existingClaim: ""
        storageClass: ""
        subPath: ""
        accessMode: ReadWriteOnce
        size: 1Gi
        annotations: {}
      redis:
        existingClaim: ""
        storageClass: ""
        subPath: ""
        accessMode: ReadWriteOnce
        size: 1Gi
        annotations: {}
      trivy:
        existingClaim: ""
        storageClass: ""
        subPath: ""
        accessMode: ReadWriteOnce
        size: 5Gi
        annotations: {}
