app-template:
  controllers:
    cloudflared:
      replicas: 3
      containers:
        app:
          image:
            repository: docker.io/cloudflare/cloudflared
            tag: 2025.2.1
          args:
            - tunnel
            - run
            - --parallel=4
            - --protocol=quic
            - --config=/etc/cloudflared/config.yaml
  configMaps:
    config:
      enabled: true
      data:
        config.yaml: |
          tunnel: homelab
          credentials-file: /etc/cloudflared/credentials.json
          metrics: 0.0.0.0:2000
          no-autoupdate: true
          grace-period: 30s
          retries: 10
          protocol: quic
          ingress:
            - hostname: '*.fullstackjam.com'
              service: https://ingress-nginx-controller.ingress-nginx
              originRequest:
                noTLSVerify: true
                keepAlive-connections: 100
                keepAlive-timeout: 30s
            - service: http_status:404
  persistence:
    config:
      enabled: true
      type: configMap
      name: cloudflared-config
      globalMounts:
        - path: /etc/cloudflared/config.yaml
          subPath: config.yaml
    credentials:
      enabled: true
      type: secret
      name: cloudflared-credentials
      globalMounts:
        - path: /etc/cloudflared/credentials.json
          subPath: credentials.json
