metrics-server:
  replicas: 3
  args:
    - --kubelet-insecure-tls
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --kubelet-use-node-status-port
    - --metric-resolution=10s
    - --kubelet-request-timeout=2s
