woodpecker:
  agent:
    replicaCount: 2
    env:
      WOODPECKER_BACKEND_K8S_STORAGE_RWX: false
      # Agents will spawn pods to run workflow steps using the
      # Kubernetes backend instead of running them directly on
      # the agent pod, so we can run many workflows per agent.
      WOODPECKER_MAX_WORKFLOWS: 10
    mapAgentSecret: false
    extraSecretNamesForEnvFrom: ["woodpecker-secret"]
  server:
    createAgentSecret: false
    env:
      WOODPECKER_HOST: https://ci.fullstackjam.com
      WOODPECKER_WEBHOOK_HOST: http://woodpecker-server.woodpecker
      WOODPECKER_GITEA: true
      WOODPECKER_GITEA_URL: https://git.fullstackjam.com
      WOODPECKER_OPEN: true
      WOODPECKER_ADMIN: gitea_admin
    extraSecretNamesForEnvFrom: ["woodpecker-secret"]
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: "homelab-tunnel.fullstackjam.com"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      ingressClassName: nginx
      hosts:
        - host: &host ci.fullstackjam.com
          paths:
            - path: /
      tls:
        - secretName: woodpecker-tls-certificate
          hosts:
            - *host
