#!/bin/sh

echo "WARNING: gitea_admin can do anything in the cluster, only use it for just enough initial setup or in emergencies." >&2
export KUBECONFIG=./kubeconfig.yaml
kubectl get secret --namespace gitea gitea-admin-secret -o jsonpath="{.data.password}" | base64 --decode
