
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-autoally-backend-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  data:
    - secretKey: SLACK_SIGNING_SECRET
      remoteRef:
        key: external
        property: SLACK_SIGNING_SECRET
    - secretKey: SLACK_BOT_TOKEN
      remoteRef:
        key: external
        property: SLACK_BOT_TOKEN
