annotations:
  artifacthub.io/changes: |
    - Fix correct indentation in client-daemonset.yaml hostPath.
  artifacthub.io/images: |
    - name: manager
      image: dragonflyoss/manager:v2.2.1
    - name: scheduler
      image: dragonflyoss/scheduler:v2.2.1
    - name: client
      image: dragonflyoss/client:v0.2.19
    - name: seed-client
      image: dragonflyoss/client:v0.2.19
    - name: dfinit
      image: dragonflyoss/dfinit:v0.2.19
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/dragonflyoss/helm-charts
    - name: Source
      url: https://github.com/dragonflyoss/dragonfly
    - name: Source
      url: https://github.com/dragonflyoss/client
apiVersion: v2
appVersion: 2.2.1
dependencies:
- condition: mysql.enable
  name: mysql
  repository: https://charts.bitnami.com/bitnami
  version: 10.1.1
- condition: redis.enable
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 20.11.4
description: Dragonfly is an intelligent P2P based image and file distribution system
home: https://d7y.io/
icon: https://raw.githubusercontent.com/dragonflyoss/dragonfly/main/docs/images/logo/dragonfly.svg
keywords:
- dragonfly
- d7y
- P2P
- image
maintainers:
- email: gaius.qi@gmail.com
  name: gaius-qi
- email: aiopsclub@163.com
  name: yxxhero
- email: majinjing3@gmail.com
  name: jim3ma
name: dragonfly
sources:
- https://github.com/dragonflyoss/dragonfly
- https://github.com/dragonflyoss/client
type: application
version: 1.3.16
